const technologies = [
  { name: 'Android', regex: /android/i },
  { name: 'Angular', regex: /angular/i },
  { name: 'Apache', regex: /apache/i },
  { name: 'AWS', regex: /aws/i },
  { name: 'Ansible', regex: /ansible/i },
  { name: 'Chef', regex: /chef/i },
  { name: 'Azure', regex: /azure/i },
  { name: 'Bitcoin', regex: /(bitcoin|bit coin)/i },
  { name: 'Blockchain', regex: /blockchain/i },
  { name: 'CSS', regex: /css/i },
  { name: 'C#', regex: /c#/i },
  { name: 'Django', regex: /(django)/i },
  { name: 'Docker', regex: /docker/i },
  { name: 'Electron', regex: /electron/i },
  { name: 'Elixir', regex: /elixir/i },
  { name: 'Express', regex: /(express)/i },
  { name: 'Go', regex: /(Go\s+|golang|Golang|GOLANG)/ },
  { name: 'Google Cloud', regex: /google\s{0,1}cloud/i },
  { name: 'GraphQL', regex: /graphql/i },
  { name: 'HTML', regex: /html/i },
  { name: 'iOS', regex: /[^A-z]ios[^A-z]/i },
  { name: 'Java', regex: /(?!javascript)java/i },
  { name: 'Kotlin', regex: /kotlin/i },
  { name: 'Kubernetes', regex: /(kubernetes|k8)/i },
  {
    name: 'JavaScript',
    regex: /(javascript|js|es5|es6|es7|es2015|es2016|es2017|ecmascript)/i,
  },
  { name: 'Laravel', regex: /(laravel)/i },
  { name: 'Linux', regex: /linux/i },
  { name: 'NativeScript', regex: /(nativescript|native script)/i },
  { name: 'NestJS', regex: /(nestjs)/i },
  { name: '.NET', regex: /\.net/i },
  { name: 'NGINX', regex: /nginx/i },
  { name: 'Node', regex: /node/i },
  { name: 'PHP', regex: /php/i },
  { name: 'Puppet', regex: /puppet/i },
  { name: 'Python', regex: /python/i },
  { name: 'React', regex: /react/i },
  { name: 'React Native', regex: /(reactnative|react native)/i },
  { name: 'Ruby on Rails', regex: /(rails|ror)/i },
  { name: 'Ruby', regex: /ruby/i },
  { name: 'Rust', regex: /rust/i },
  { name: 'Scala', regex: /scala/i },
  { name: 'Svelte', regex: /svelte/i },
  { name: 'SQL', regex: /sql/i },
  { name: 'TypeScript', regex: /typescript/i },
  { name: 'Web', regex: /web/i },
  { name: 'WordPress', regex: /(word press | wordpress)/i },
  { name: 'Vue', regex: /vue/i },
];

export default function extractTechnologiesFromString(str: string): string[] {
  return technologies
    .filter(({ regex }) => regex.test(str))
    .map(({ name }) => name);
}
